export interface PrintData {
  companyName?: string;
  farmName?: string;
  shedName?: string;
  batchNumber?: string;
  date?: string;
  module: string;
  entryDetails: Record<string, string | number | undefined>;
  generatedBy?: string;
}

export function printRecord(data: PrintData) {
  const rows = Object.entries(data.entryDetails)
    .filter(([, v]) => v !== undefined && v !== "")
    .map(
      ([k, v]) =>
        `<tr><td style="padding:4px 8px;font-weight:600;color:#555;">${k}</td><td style="padding:4px 8px;">${v}</td></tr>`,
    )
    .join("");

  const html = `<!DOCTYPE html><html><head><title>Print - ${data.module}</title>
  <style>body{font-family:Arial,sans-serif;font-size:13px;color:#222;padding:24px;}
  h2{color:#16a34a;margin:0 0 4px;}p{margin:2px 0;color:#555;}table{width:100%;border-collapse:collapse;margin-top:16px;}
  tr:nth-child(even){background:#f9f9f9;}td{border:1px solid #e5e7eb;}
  .footer{margin-top:20px;font-size:11px;color:#888;border-top:1px solid #e5e7eb;padding-top:8px;}
  </style></head><body>
  <h2>Poultrix — ${data.module}</h2>
  ${data.companyName ? `<p><strong>Company:</strong> ${data.companyName}</p>` : ""}
  ${data.farmName ? `<p><strong>Farm:</strong> ${data.farmName}</p>` : ""}
  ${data.shedName ? `<p><strong>Shed:</strong> ${data.shedName}</p>` : ""}
  ${data.batchNumber ? `<p><strong>Batch:</strong> ${data.batchNumber}</p>` : ""}
  ${data.date ? `<p><strong>Date:</strong> ${data.date}</p>` : ""}
  <table><tbody>${rows}</tbody></table>
  <div class="footer">
    <p>Generated By: ${data.generatedBy || "Unknown"}</p>
    <p>Timestamp: ${new Date().toLocaleString("en-IN")}</p>
  </div>
  </body></html>`;

  const win = window.open("", "_blank", "width=800,height=600");
  if (win) {
    win.document.write(html);
    win.document.close();
    win.focus();
    win.print();
    win.close();
  }
}
