/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FarmId = IDL.Nat;
export const ShedId = IDL.Nat;
export const BatchId = IDL.Nat;
export const Batch = IDL.Record({
  'id' : BatchId,
  'status' : IDL.Text,
  'shedId' : ShedId,
  'hatcheryName' : IDL.Text,
  'chicksQty' : IDL.Nat,
  'placementDate' : IDL.Int,
  'birdsAlive' : IDL.Nat,
  'totalPlacementCost' : IDL.Nat,
  'batchNumber' : IDL.Text,
  'transportCost' : IDL.Nat,
  'breedType' : IDL.Text,
  'chicksRate' : IDL.Nat,
  'farmId' : FarmId,
});
export const Farm = IDL.Record({
  'id' : FarmId,
  'name' : IDL.Text,
  'location' : IDL.Text,
  'totalCapacity' : IDL.Nat,
});
export const Shed = IDL.Record({
  'id' : ShedId,
  'name' : IDL.Text,
  'capacity' : IDL.Nat,
  'farmId' : FarmId,
});

export const idlService = IDL.Service({
  'createBatch' : IDL.Func(
      [
        IDL.Int,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        FarmId,
        ShedId,
      ],
      [BatchId],
      [],
    ),
  'createFarm' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [FarmId], []),
  'createShed' : IDL.Func([FarmId, IDL.Text, IDL.Nat], [ShedId], []),
  'getBatch' : IDL.Func([BatchId], [IDL.Opt(Batch)], ['query']),
  'getFarm' : IDL.Func([FarmId], [IDL.Opt(Farm)], ['query']),
  'getShed' : IDL.Func([ShedId], [IDL.Opt(Shed)], ['query']),
  'updateBirdsAlive' : IDL.Func([BatchId, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FarmId = IDL.Nat;
  const ShedId = IDL.Nat;
  const BatchId = IDL.Nat;
  const Batch = IDL.Record({
    'id' : BatchId,
    'status' : IDL.Text,
    'shedId' : ShedId,
    'hatcheryName' : IDL.Text,
    'chicksQty' : IDL.Nat,
    'placementDate' : IDL.Int,
    'birdsAlive' : IDL.Nat,
    'totalPlacementCost' : IDL.Nat,
    'batchNumber' : IDL.Text,
    'transportCost' : IDL.Nat,
    'breedType' : IDL.Text,
    'chicksRate' : IDL.Nat,
    'farmId' : FarmId,
  });
  const Farm = IDL.Record({
    'id' : FarmId,
    'name' : IDL.Text,
    'location' : IDL.Text,
    'totalCapacity' : IDL.Nat,
  });
  const Shed = IDL.Record({
    'id' : ShedId,
    'name' : IDL.Text,
    'capacity' : IDL.Nat,
    'farmId' : FarmId,
  });
  
  return IDL.Service({
    'createBatch' : IDL.Func(
        [
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          FarmId,
          ShedId,
        ],
        [BatchId],
        [],
      ),
    'createFarm' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [FarmId], []),
    'createShed' : IDL.Func([FarmId, IDL.Text, IDL.Nat], [ShedId], []),
    'getBatch' : IDL.Func([BatchId], [IDL.Opt(Batch)], ['query']),
    'getFarm' : IDL.Func([FarmId], [IDL.Opt(Farm)], ['query']),
    'getShed' : IDL.Func([ShedId], [IDL.Opt(Shed)], ['query']),
    'updateBirdsAlive' : IDL.Func([BatchId, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };