/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Batch {
  'id' : BatchId,
  'status' : string,
  'shedId' : ShedId,
  'hatcheryName' : string,
  'chicksQty' : bigint,
  'placementDate' : bigint,
  'birdsAlive' : bigint,
  'totalPlacementCost' : bigint,
  'batchNumber' : string,
  'transportCost' : bigint,
  'breedType' : string,
  'chicksRate' : bigint,
  'farmId' : FarmId,
}
export type BatchId = bigint;
export interface Farm {
  'id' : FarmId,
  'name' : string,
  'location' : string,
  'totalCapacity' : bigint,
}
export type FarmId = bigint;
export interface Shed {
  'id' : ShedId,
  'name' : string,
  'capacity' : bigint,
  'farmId' : FarmId,
}
export type ShedId = bigint;
export interface _SERVICE {
  'createBatch' : ActorMethod<
    [bigint, string, string, bigint, bigint, bigint, bigint, FarmId, ShedId],
    BatchId
  >,
  'createFarm' : ActorMethod<[string, string, bigint], FarmId>,
  'createShed' : ActorMethod<[FarmId, string, bigint], ShedId>,
  'getBatch' : ActorMethod<[BatchId], [] | [Batch]>,
  'getFarm' : ActorMethod<[FarmId], [] | [Farm]>,
  'getShed' : ActorMethod<[ShedId], [] | [Shed]>,
  'updateBirdsAlive' : ActorMethod<[BatchId, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];